[semantic_release]
version_variables = ["VERSION:*:nf"]
allow_zero_version = true
major_on_zero = false
tag_format = "v{version}"
commit_message = "chore(release): {version}"
commit_parser = "conventional"

[semantic_release.branches.main]
match = "main"
prerelease = false

[semantic_release.changelog]
mode = "update"
insertion_flag = "<!-- version list -->"

[semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md"

[semantic_release.publish]
upload_to_vcs_release = false
